from __future__ import annotations

import threading
import time

import pydirectinput


class InputController:
    """
    Tracks only keys/buttons generated by this app so an emergency stop can
    release them without interfering with keys the user is physically holding.
    """

    def __init__(self):
        pydirectinput.PAUSE = 0.0
        self.enabled = False
        self._keys_down: set[str] = set()
        self._mouse_down: set[str] = set()
        self._lock = threading.RLock()

    def set_enabled(self, value: bool) -> None:
        with self._lock:
            self.enabled = bool(value)
            if not self.enabled:
                self.release_all()

    def tap_key(self, key: str, duration: float = 0.08) -> None:
        with self._lock:
            if not self.enabled:
                raise RuntimeError("Input control is disabled.")
        self.key_down(key)
        try:
            time.sleep(max(0.01, min(float(duration), 2.0)))
        finally:
            self.key_up(key)

    def key_down(self, key: str) -> None:
        with self._lock:
            if not self.enabled:
                raise RuntimeError("Input control is disabled.")
            pydirectinput.keyDown(key)
            self._keys_down.add(key)

    def key_up(self, key: str) -> None:
        with self._lock:
            try:
                pydirectinput.keyUp(key)
            finally:
                self._keys_down.discard(key)

    def click(self, x: int | None = None, y: int | None = None, button: str = "left") -> None:
        with self._lock:
            if not self.enabled:
                raise RuntimeError("Input control is disabled.")
            pydirectinput.click(x=x, y=y, button=button)

    def release_all(self) -> None:
        with self._lock:
            for key in list(self._keys_down):
                try:
                    pydirectinput.keyUp(key)
                except Exception:
                    pass
            self._keys_down.clear()

            for button in list(self._mouse_down):
                try:
                    pydirectinput.mouseUp(button=button)
                except Exception:
                    pass
            self._mouse_down.clear()
